
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.2.0
  hooks:
  - id: trailing-whitespace

- repo: https://github.com/jumanjihouse/pre-commit-hooks.git
  rev: 2.1.6
  hooks:
  - id: shellcheck

