
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
  - id: trailing-whitespace

- repo: https://github.com/jumanjihouse/pre-commit-hooks.git
  rev: 3.0.0
  hooks:
  - id: shellcheck
    exclude: \.zsh$

- repo: https://github.com/Koihik/LuaFormatter.git
  rev: 29afe1046ad015de96ffdb6d361a21882356e801
  hooks:
  - id: luaformatter
