bind-key C-b last-window
bind -n C-k send-keys C-l \; clear-history

set -g mouse on

set -g default-terminal "screen-256color"

# Embedded sessions get C-a
bind-key -n C-a send-prefix

set -g pane-border-status top

